Repository asimov-platform/protoflow, pull requests merged in 2024-11, with the labels that each got.

#3 Implement a `WriteFile` block
  lib/protoflow-blocks/src/block_tag.rs
  lib/protoflow-blocks/src/blocks/sys.rs
  lib/protoflow-blocks/src/blocks/sys/write_file.rs
  lib/protoflow-blocks/src/system.rs
Labels: enhancement, good first issue

#4 Implement a `ReadFile` block
  lib/protoflow-blocks/Cargo.toml
  lib/protoflow-blocks/src/blocks/sys/read_file.rs
Labels: enhancement

#6 Implement a `DecodeJson` block
  README.md
  lib/protoflow-blocks/Cargo.toml
  lib/protoflow-blocks/doc/io/decode_json.mmd
  lib/protoflow-blocks/doc/io/decode_json.seq.mmd
  lib/protoflow-blocks/src/blocks/io.rs
  lib/protoflow-blocks/src/blocks/io/decode_json.rs
  lib/protoflow-blocks/src/lib.rs
  lib/protoflow-blocks/src/system.rs
  lib/protoflow-blocks/tests/json_roundtrip.rs
Labels: enhancement

#7 Fix the permissions for the release job
  .github/workflows/release.yaml
Labels: bug

#2 Implement blocking AsyncBlock trait
  lib/protoflow-blocks/Cargo.toml
  lib/protoflow-blocks/src/system.rs
  lib/protoflow-core/Cargo.toml
  lib/protoflow-core/src/async_block.rs
  lib/protoflow-core/src/block.rs
  lib/protoflow-core/src/lib.rs
  lib/protoflow-core/src/prelude.rs
  lib/protoflow-core/src/runtime.rs
  lib/protoflow-core/src/runtimes/std.rs
  lib/protoflow-core/src/system.rs
  lib/protoflow/Cargo.toml
  lib/protoflow/examples/async/main.rs
Labels: enhancement

#9 Implement `ConcatStrings` and `SplitString`
  README.md
  lib/protoflow-blocks/doc/text/concat_strings.mmd
  lib/protoflow-blocks/doc/text/concat_strings.seq.mmd
  lib/protoflow-blocks/doc/text/split_string.mmd
  lib/protoflow-blocks/doc/text/split_string.seq.mmd
  lib/protoflow-blocks/src/block_config.rs
  lib/protoflow-blocks/src/block_tag.rs
  lib/protoflow-blocks/src/blocks/text.rs
  lib/protoflow-blocks/src/blocks/text/concat_strings.rs
  lib/protoflow-blocks/src/blocks/text/split_string.rs
  lib/protoflow-blocks/src/lib.rs
  lib/protoflow-blocks/src/system.rs
Labels: enhancement

#13 Add missing `DecodeJson` tags
  lib/protoflow-blocks/src/block_config.rs
  lib/protoflow-blocks/src/block_tag.rs
  lib/protoflow-blocks/src/blocks/io.rs
Labels: bug

#17 Implement `DecodeCSV` and `EncodeCSV`
  README.md
  lib/protoflow-blocks/Cargo.toml
  lib/protoflow-blocks/doc/text/decode_csv.mmd
  lib/protoflow-blocks/doc/text/decode_csv.seq.mmd
  lib/protoflow-blocks/doc/text/encode_csv.mmd
  lib/protoflow-blocks/doc/text/encode_csv.seq.mmd
  lib/protoflow-blocks/src/block_config.rs
  lib/protoflow-blocks/src/block_tag.rs
  lib/protoflow-blocks/src/blocks/text.rs
  lib/protoflow-blocks/src/blocks/text/decode_csv.rs
  lib/protoflow-blocks/src/blocks/text/encode_csv.rs
  lib/protoflow-blocks/src/lib.rs
  lib/protoflow-blocks/src/system.rs
  lib/protoflow-core/src/async_block.rs
  lib/protoflow-core/src/block.rs
  lib/protoflow/examples/async/main.rs
Labels: enhancement

#11 Implement `DecodeHex`
  README.md
  lib/protoflow-blocks/doc/io/decode_hex.mmd
  lib/protoflow-blocks/doc/io/decode_hex.seq.mmd
  lib/protoflow-blocks/src/block_config.rs
  lib/protoflow-blocks/src/block_tag.rs
  lib/protoflow-blocks/src/blocks/io.rs
  lib/protoflow-blocks/src/blocks/io/decode_hex.rs
  lib/protoflow-blocks/src/lib.rs
  lib/protoflow-blocks/src/system.rs
Labels: enhancement

#10 Implement `ReadSocket` and `WriteSocket`
  README.md
  lib/protoflow-blocks/doc/sys/read_socket.mmd
  lib/protoflow-blocks/doc/sys/read_socket.seq.mmd
  lib/protoflow-blocks/doc/sys/write_socket.mmd
  lib/protoflow-blocks/doc/sys/write_socket.seq.mmd
  lib/protoflow-blocks/src/block_config.rs
  lib/protoflow-blocks/src/block_tag.rs
  lib/protoflow-blocks/src/blocks/sys.rs
  lib/protoflow-blocks/src/blocks/sys/read_socket.rs
  lib/protoflow-blocks/src/blocks/sys/write_socket.rs
  lib/protoflow-blocks/src/lib.rs
  lib/protoflow-blocks/src/system.rs
Labels: enhancement

#18 Support the MD5, SHA-1, and SHA-256 hashing algorithms
  lib/protoflow-blocks/Cargo.toml
  lib/protoflow-blocks/src/block_config.rs
  lib/protoflow-blocks/src/block_tag.rs
  lib/protoflow-blocks/src/blocks/hash.rs
  lib/protoflow-blocks/src/blocks/hash/hash.rs
  lib/protoflow-blocks/src/lib.rs
  lib/protoflow-blocks/src/system.rs
  lib/protoflow-blocks/src/types.rs
  lib/protoflow-blocks/src/types/hash_algorithm.rs
  lib/protoflow-core/src/prelude.rs
Labels: enhancement
