Repository asimov-platform/protoflow, pull requests merged in 2024-12, with the labels that each got.

#20 Fix stdout/stderr synchronization
  lib/protoflow-blocks/src/blocks/sys/write_stderr.rs
  lib/protoflow-blocks/src/blocks/sys/write_stdout.rs
Labels: bug

#26 Implement CI for pull requests
  .github/workflows/ci.yaml
Labels: enhancement

#28 Improve CI workflows
  .github/workflows/ci.yaml
Labels: bug, enhancement

#33 Fix tests in CI
  .github/workflows/ci.yaml
Labels: bug

#31 Remove duplicate hash feature configurations
  lib/protoflow-blocks/src/block_config.rs
Labels: bug

#32 Add Serde, std, and tracing feature gates
  lib/protoflow-blocks/src/block_tag.rs
  lib/protoflow-blocks/src/blocks/io/decode_hex.rs
  lib/protoflow-blocks/src/blocks/sys.rs
  lib/protoflow-blocks/src/blocks/sys/read_socket.rs
  lib/protoflow-blocks/src/blocks/sys/write_socket.rs
  lib/protoflow-blocks/src/lib.rs
  lib/protoflow-blocks/src/system.rs
Labels: bug

#12 Separate system-building from the transport layer
  lib/protoflow-blocks/src/blocks/sys/read_file.rs
  lib/protoflow-blocks/src/system.rs
  lib/protoflow-blocks/tests/json_roundtrip.rs
  lib/protoflow-core/src/input_port.rs
  lib/protoflow-core/src/output_port.rs
  lib/protoflow-core/src/prelude.rs
  lib/protoflow-core/src/system.rs
  lib/protoflow/tests/mpsc.rs
  lib/protoflow/tests/zst.rs
Labels: enhancement
